// Catalogo migrado desde el JSON de WhatsApp (Anexo de la especificacion).
//
// NOTA: el documento de especificacion dice "59 productos" pero el array
// original tiene 61 entradas (coincide con las 61 fotos unicas encontradas
// tras deduplicar por hash en catalog-source-photos/). Se migraron las 61.
//
// `foto` referencia el nombre de archivo CANONICO dentro de
// catalog-source-photos/ despues de deduplicar (ver scripts/dedupe-photos.mjs).
// Varios productos comparten nombre ("Nike SB Dunk", "Vans Sk8 High") porque
// asi estaban cargados por separado en el catalogo de WhatsApp original.

export const catalogSource = [
  { marca: "Adidas", nombre: "Samba Clásicas", categoria: "zapatillas", precio_ars: 49000, talles: ["34", "36", "37", "38"], estado: "disponible", foto: "Adidas Samba Clasicas.jpg" },
  { marca: "Adidas", nombre: "Samba Negro Calidad Premium", categoria: "zapatillas", precio_ars: 49000, talles: ["35", "38"], estado: "disponible", foto: "Adidas Samba Negro Calidad Premium.jpg" },
  { marca: "Adidas", nombre: "Samba XL Beige/Chocolate", categoria: "zapatillas", precio_ars: 49000, talles: ["34", "35", "37", "38", "39"], estado: "disponible", foto: "Adidas Samba XL Beige Chocolate.jpg" },
  { marca: "Vans", nombre: "Hylane Beige Chocolate", categoria: "zapatillas", precio_ars: 55000, talles: ["34", "35"], estado: "disponible", foto: "Vans Hylane Beige Chocolate.jpg" },
  { marca: "Adidas", nombre: "Forum", categoria: "zapatillas", precio_ars: 55000, talles: ["39", "40", "41", "42", "43"], estado: "disponible", foto: "Adidas Forum.jpg" },
  { marca: "Vans", nombre: "Old Skool", categoria: "zapatillas", precio_ars: 45000, talles: [], estado: "agotado", foto: "Vans Old Skool.jpg" },
  { marca: "Vans", nombre: "Knu Total Black", categoria: "zapatillas", precio_ars: 49000, talles: ["38", "39", "40", "41", "42"], estado: "disponible", foto: "Vans Knu Total Black.jpg" },
  { marca: "Vans", nombre: "Knu Negro Beige", categoria: "zapatillas", precio_ars: 49000, talles: ["40"], estado: "disponible", foto: "VANS KNU NEGRO BEIGE.jpg" },
  { marca: "Adidas", nombre: "Forum Total White", categoria: "zapatillas", precio_ars: 49000, talles: ["39", "41", "42", "43"], estado: "disponible", foto: "ADIDAS FORUM TOTAL WHITE.jpg" },
  { marca: "Adidas", nombre: "Adizero Boston 11", categoria: "zapatillas", precio_ars: 45000, talles: ["39", "40", "41"], estado: "disponible", foto: "ADIDAS ADIZERO BOSTON 11.jpg" },
  { marca: "Vans", nombre: "Hylane Gris Negro", categoria: "zapatillas", precio_ars: 55000, talles: [], estado: "agotado", foto: "VANS HYLANE GRIS NEGRO.jpg" },
  { marca: "Vans", nombre: "Knu Gris", categoria: "zapatillas", precio_ars: 49000, talles: ["35", "36", "37", "38", "39", "41"], estado: "disponible", foto: "VANS KNU GRIS.jpg" },
  { marca: "Vans", nombre: "Hylane Total Black", categoria: "zapatillas", precio_ars: 55000, talles: ["40"], estado: "disponible", foto: "VANS HYLANE TOTAL BLACK.jpg" },
  { marca: "Nike", nombre: "SB Dunk Chocolate", categoria: "zapatillas", precio_ars: 49000, talles: ["37"], estado: "disponible", foto: "NIKE SB DUNK CHOCOLATE.jpg" },
  { marca: "Nike", nombre: "Pegasus", categoria: "zapatillas", precio_ars: 45000, talles: ["40", "43"], estado: "disponible", foto: "NIKE PEGASUS.jpg" },
  { marca: "Nike", nombre: "SB Dunk", categoria: "zapatillas", precio_ars: 49000, talles: [], estado: "agotado", foto: "NIKE SB DUNK (1).jpg" },
  { marca: "Nike", nombre: "SB Dunk", categoria: "zapatillas", precio_ars: 49000, talles: ["34", "36", "37", "38"], estado: "disponible", foto: "NIKE SB DUNK.jpg" },
  { marca: "Adidas", nombre: "Forum Blanco Negro", categoria: "zapatillas", precio_ars: 49000, talles: [], estado: "agotado", foto: "ADIDAS FORUM BLANCO NEGRO.jpg" },
  { marca: "Vans", nombre: "Sk8 High", categoria: "zapatillas", precio_ars: 45000, precio_anterior_ars: 48000, en_oferta: true, talles: ["37", "38", "39", "40", "41"], estado: "disponible", foto: "VANS SK8 HIGH.jpg" },
  { marca: "Vans", nombre: "Ultrarange VR3", categoria: "zapatillas", precio_ars: 49000, talles: ["39", "40", "41", "42", "43"], estado: "disponible", foto: "VANS ULTRARANGE VR3.jpg" },
  { marca: "Vans", nombre: "Hylane Negro Gris", categoria: "zapatillas", precio_ars: 53000, talles: ["40"], estado: "disponible", foto: "VANS HYLANE NEGRO GRIS.jpg" },
  { marca: "New Balance", nombre: "530", categoria: "zapatillas", precio_ars: 52000, talles: ["35", "36", "37", "38", "39"], estado: "disponible", foto: "NEW BALANCE 530.jpg" },
  { marca: "Vans", nombre: "Knu (importadas Brasil)", categoria: "zapatillas", precio_ars: 49000, talles: ["34", "35", "36", "37", "38", "39", "41", "42"], estado: "disponible", nota: "Calcular un talle menos que el habitual", foto: "VANS KNU (variante).jpg" },
  { marca: "Vans", nombre: "Hylane Beige Gris", categoria: "zapatillas", precio_ars: 55000, talles: ["40", "41"], estado: "disponible", foto: "VANS HYLANE BEIGE GRIS.jpg" },
  { marca: "Vans", nombre: "Hylane Beige", categoria: "zapatillas", precio_ars: 55000, talles: ["39", "40", "41", "42"], estado: "disponible", foto: "VANS HYLANE BEIGE.jpg" },
  { marca: "Vans", nombre: "Ultrarange 3D", categoria: "zapatillas", precio_ars: 49000, talles: [], estado: "agotado", foto: "VANS ULTRARANGE 3D.jpg" },
  { marca: "Adidas", nombre: "Campus Negro/Blanco", categoria: "zapatillas", precio_ars: 49000, talles: ["34", "35"], estado: "disponible", foto: "ADIDAS CAMPUS Negro-blanco.jpg" },
  { marca: "Vans", nombre: "Ultrarange 3D Gris", categoria: "zapatillas", precio_ars: 49000, talles: ["37"], estado: "disponible", foto: "VANS ULTRARANGE 3D Gris.jpg" },
  { marca: "Adidas", nombre: "Samba Chocolate", categoria: "zapatillas", precio_ars: 49000, talles: ["35"], estado: "disponible", foto: "ADIDAS SAMBA CHOCOLATE.jpg" },
  { marca: "Adidas", nombre: "Spezial", categoria: "zapatillas", precio_ars: 49000, talles: ["35"], estado: "disponible", foto: "ADIDAS SPEZIAL.jpg" },
  { marca: "Nike", nombre: "SB Dunk Total White", categoria: "zapatillas", precio_ars: 49000, talles: ["38", "40", "43"], estado: "disponible", foto: "NIKE SB DUNK Total White (1).jpg" },
  { marca: "New Balance", nombre: "9060 Blanco/Gris", categoria: "zapatillas", precio_ars: 49000, talles: ["36"], estado: "disponible", foto: "NEW BALANCE 9060 Blanco-gris.jpg" },
  { marca: "Adidas", nombre: "Adizero Evo SL", categoria: "zapatillas", precio_ars: 45000, talles: ["34", "35", "36", "37", "38", "39", "40", "41", "42"], estado: "disponible", foto: "ADIDAS ADIZERO EVO SL.jpg" },
  { marca: "Vans", nombre: "Sk8 High", categoria: "zapatillas", precio_ars: 45000, precio_anterior_ars: 48000, en_oferta: true, talles: ["38", "39"], estado: "disponible", foto: "VANS SK8 HIGH (2).jpg" },
  { marca: "Jordan", nombre: "Retro 4 Negro/Blanco", categoria: "zapatillas", precio_ars: 49000, talles: ["43"], estado: "disponible", foto: "JORDAN RETRO 4 NEGRO-BLANCO.jpg" },
  { marca: "Adidas", nombre: "Duramo Speed 2", categoria: "zapatillas", precio_ars: 45000, talles: ["38", "39", "40", "41"], estado: "disponible", foto: "ADIDAS DURAMO SPEED 2.jpg" },
  { marca: "Vans", nombre: "Hylane Marino", categoria: "zapatillas", precio_ars: 55000, talles: [], estado: "agotado", foto: "VANS HYLANE MARINO.jpg" },
  { marca: "Puma", nombre: "Suede XL Clásica", categoria: "zapatillas", precio_ars: 49000, talles: ["41"], estado: "disponible", foto: "PUMA SUEDE XL CLASICA.jpg" },
  { marca: "Nike", nombre: "SB Dunk Blanco", categoria: "zapatillas", precio_ars: 49000, talles: ["38", "40", "41", "42"], estado: "disponible", foto: "NIKE SB DUNK BLANCO.jpg" },
  { marca: "Nike", nombre: "Duramo SL2", categoria: "zapatillas", precio_ars: 45000, talles: ["35", "37"], estado: "disponible", foto: "NIKE DURAMO SL2.jpg" },
  { marca: "Nike", nombre: "Travis Scott Phantom", categoria: "zapatillas", precio_ars: 49000, talles: ["38", "39", "40", "41", "42"], estado: "disponible", foto: "NIKE TRAVIS SCOTT PHANTOM.jpg" },
  { marca: "Nike", nombre: "SB Dunk Total White G5", categoria: "zapatillas", precio_ars: 49000, talles: ["38", "40", "43"], estado: "disponible", foto: "NIKE SB DUNK TOTAL WHITE G5.jpg" },
  { marca: "Adidas", nombre: "Samba XLG Clásica", categoria: "zapatillas", precio_ars: 49000, talles: ["38", "39", "40", "41", "42", "43"], estado: "disponible", foto: "ADIDAS SAMBA XLG CLASICA.jpg" },
  { marca: "Vans", nombre: "Knu Total White Eco Cuero", categoria: "zapatillas", precio_ars: 49000, talles: ["41", "42"], estado: "disponible", foto: "VANS KNU TOTAL WHITE ECO CUERO.jpg" },
  { marca: "Puma", nombre: "Suede XL Total Black", categoria: "zapatillas", precio_ars: 49000, talles: ["42"], estado: "disponible", foto: "PUMA SUEDE XL TOTAL BLACK.jpg" },
  { marca: "Vans", nombre: "Knu Negro/Blanco", categoria: "zapatillas", precio_ars: 49000, talles: ["39", "40", "41", "42"], estado: "disponible", foto: "VANS KNU Negro-blanco.jpg" },
  { marca: "Jordan", nombre: "Zapatilla", categoria: "zapatillas", precio_ars: 29000, precio_anterior_ars: 46000, en_oferta: true, talles: ["40", "42"], estado: "disponible", nota: "Nombre de modelo a confirmar con la dueña", foto: "Zapatilla JORDAN.jpg" },
  { marca: "Adidas", nombre: "Samba Blanco", categoria: "zapatillas", precio_ars: 39000, precio_anterior_ars: 49000, en_oferta: true, talles: ["38"], estado: "disponible", foto: "ADIDAS SAMBA BLANCO.jpg" },
  { marca: "Nike", nombre: "Travis Scott Reverse Mocha", categoria: "zapatillas", precio_ars: 49000, talles: ["39", "40", "41"], estado: "disponible", foto: "NIKE TRAVIS SCOTT REVERSE MOCHA.jpg" },
  { marca: "Nike", nombre: "Knit", categoria: "zapatillas", precio_ars: 29000, precio_anterior_ars: 49000, en_oferta: true, talles: ["38", "39", "41"], estado: "disponible", nota: "Talla grande, pedir 2-3 números menos", foto: "NIKE KNIT.jpg" },
  { marca: "Adidas", nombre: "Pantalón Slim", categoria: "indumentaria", precio_ars: 29000, talles: [], estado: "disponible", foto: "ADIDAS PANTALON SLIM.jpg" },
  { marca: "Adidas", nombre: "Pantalón Algodón", categoria: "indumentaria", precio_ars: 29000, talles: [], estado: "disponible", foto: "ADIDAS PANTALON ALGODON.jpg" },
  { marca: "Shoter", nombre: "Kit Limpieza Premium", categoria: "accesorios", precio_ars: 35000, talles: [], estado: "disponible", foto: "SHOTER KIT LIMPIEZA PREMIUM.jpg" },
  { marca: "Vans", nombre: "Knu Grafito", categoria: "zapatillas", precio_ars: 49000, talles: ["40"], estado: "disponible", foto: "VANS KNU GRAFITO.jpg" },
  { marca: "Adidas", nombre: "Supernova", categoria: "zapatillas", precio_ars: 45000, talles: ["41", "42"], estado: "disponible", foto: "ADIDAS SUPERNOVA.jpg" },
  { marca: "Vans", nombre: "Knu Negra Suela Caramelo", categoria: "zapatillas", precio_ars: 49000, talles: ["41"], estado: "disponible", foto: "VANS KNU Negra Suela Caramelo.jpg" },
  { marca: "Shoter", nombre: "Repuesto Limpieza Espuma", categoria: "accesorios", precio_ars: null, talles: [], estado: "agotado", foto: "SHOTER REPUESTO LIMPIEZA ESPUMA.jpg" },
  { marca: "Shoter", nombre: "Impermeabilizante", categoria: "accesorios", precio_ars: 29000, precio_tarjeta_ars: 34000, talles: [], estado: "disponible", foto: "SHOTER IMPERMEABILIZANTE.jpg" },
  { marca: "Adidas", nombre: "Adilette Beige", categoria: "zapatillas", precio_ars: 18000, precio_anterior_ars: 29000, en_oferta: true, talles: ["33/34", "35/36"], estado: "disponible", foto: "ADIDAS ADILETTE Beige.jpg" },
  { marca: "Nike", nombre: "SB Dunk Total White", categoria: "zapatillas", precio_ars: 46000, talles: ["43"], estado: "disponible", foto: "NIKE SB DUNK Total White (2).jpg" },
  { marca: "Adidas", nombre: "2000", categoria: "zapatillas", precio_ars: 53000, talles: ["40"], estado: "disponible", nota: "Cargado como \"Adi 2000\" en el catálogo original", foto: "ADI 2000.jpg" },
];
